### ISSUE TITLE
Get single currency balance

### ISSUE THREAD

**Issue by zh68319220** [gateio/gateapi-nodejs#11]
I want to get single currency balance like "SIN" balance.
But there is just "GET /wallet/total_balance" to get total balance,this endpoint returns an approximate sum of exchanged amount from all currencies to input currency for each account.
Is there any way to get it?
Thank You!

**Comment by revilwang** [comment]
What are you trying to do? If you need to retrieve currency balance in spot, futures, or other accounts, you should use the corresponding API. `GET /wallet/total_balance`, as it said, is total approximate sum.
