### ISSUE TITLE
提现安全审核

### ISSUE THREAD

**Issue by zh68319220** [gateio/gateapi-nodejs#12]
每次我用gateapi进行提现操作，结果返回了请求成功，但是我每次的提现单号都会进入1~8小时的安全审核状态，让我人工处理。
我检查了平台apiv4的白名单和权限都没问题。
请问下有什么办法能够避免这种情况呢？

**Comment by revilwang** [comment]
请将个人的用户 id 发送至 dev@mail.gate.io ，我们来协助看一下

**Comment by zh68319220** [comment]
> 请将个人的用户 id 发送至 [dev@mail.gate.io](mailto:dev@mail.gate.io) ，我们来协助看一下

已发送至该邮箱，麻烦帮忙看一下，感谢！

**Comment by revilwang** [comment]
最近为了防钓鱼等安全问题，对部分api提现用户增强了安全审核，如果对该结果有疑问，可以从官网首页入口直接联系客服去咨询
