### ISSUE TITLE
Invalid time range

### ISSUE THREAD

**Issue by masafumimori** [gateio/gateapi-nodejs#13]
Hello, I tried to fetch my trade history by calling ”[new GateApi.SpotApi(client).listMyTrades(currencyPair, options)](https://github.com/gateio/gateapi-nodejs/blob/master/docs/SpotApi.md#listMyTrades)" with specifying time range.

But I got an error response saying `data: { label: 'INVALID_PARAM_VALUE', message: 'invalid time range' }`.
I specified "from: 1648772732" and "to: 1652771175", which is from 4/1 to 5/17.

It works when I don't specify the "to" param but it only gives me trade history for one week since 4/1.

Is there any max time range we can specify?
How long can I specify the time range?

Thank you.

**Comment by revilwang** [comment]
Try to set your range shorter, 30 days at most

**Comment by masafumimori** [comment]
@revilwang 
Thanks!
I thought there were some limits but I couldn't find info about it.
