### ISSUE TITLE
listMyTrades call immediately after closed IOC order returns empty array

### ISSUE THREAD

**Issue by jasan-s** [gateio/gateapi-nodejs#2]
Scenario:

I place a IOC order using `createOrder` , `status === closed` in response, then immediately I call `listMyTrades` using the order crypto_pair and the order_id.  

Expected: the `listMyTrades` request should return trades array. 

Actual: Response is an empty array

If i wait few seconds and call the `listMyTrades`  again using the order crypto_pair and the order_id I correctly recieve the trades in the response. 

Is this the correct behavior?

**Comment by revilwang** [comment]
Yes, order trades will be shortly delayed

**Comment by jasan-s** [comment]
Not ideal but thanks for clarifying.
