### ISSUE TITLE
How to authorize with gate.io api key using this lib ? 

### ISSUE THREAD

**Issue by pythonjsgo** [gateio/gateapi-nodejs#4]
How to authorize with gate.io api key using this lib ? 
// I want to do somthing like this 
const client = new GateApi.ApiClient("API_KEY");

**Comment by revilwang** [comment]
You can find it in API documents like [this](https://github.com/gateio/gateapi-nodejs/blob/master/docs/SpotApi.md#listSpotAccounts)

**Comment by pythonjsgo** [comment]
Ok, Thanks!!!
