### ISSUE TITLE
No way to create order

### ISSUE THREAD

**Issue by mrsnut** [gateio/gateapi-nodejs#5]
Hello, I want to create a spot order through this guide:
https://github.com/gateio/gateapi-nodejs/blob/master/docs/SpotApi.md#createOrder
But I am getting a error with the example code:
```js
gateSpotOrders.js:8
const order = new Order(); // Order |
              ^

ReferenceError: Order is not defined
```
https://github.com/gateio/gateapi-nodejs/blob/master/docs/Order.md

Is there any fix for this or how do I create a order? In the API its simple json but no details on how to do it with the nodejs package

**Comment by revilwang** [comment]
You need to import it from the library, like this

```typescript
import { Order } from "gate-api";
```

or you can try

```typescript
const order = new GateApi.Order();
# and set order attributes before post it to the server
# order.currency_pair = 'xxx'
# order.price = 'xxx';
# etc...
```

**Comment by mrsnut** [comment]
> You need to import it from the library, like this
> 
> ```ts
> import { Order } from "gate-api";
> ```
> 
> or you can try
> 
> ```ts
> const order = new GateApi.Order();
> // and set order attributes before post it to the server
> // order.currency_pair = 'xxx'
> // order.price = 'xxx';
> // etc...
> ```

Thank you, I have tried like this but am now getting a Axios error:
```js
	const order = new GateApi.Order();
	order.currency_pair = 'ADA_USDT';
	order.side = 'buy';
	order.amount = '1';
	order.price = '2.4';
	
	console.log(order);
	
	api.createOrder(order)
	   .then(value => console.log('API called successfully. Returned data: ', value.body),
			 error => console.error(error));
```
```json
Order {
  currency_pair: 'ADA_USDT',
  side: 'buy',
  amount: '1',
  price: '2.4'
}
```
```json
    data: {
      label: 'INVALID_REQUEST_BODY',
      message: 'Request body not conforming to schema'
    }
```
